# Generated by Django 4.2.8 on 2024-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('suspicious_text', models.TextField()),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
